source 'https://rubygems.org'

gem 'rails', '3.2.8'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'paperclip', '3.2.0'
gem 'thin', '1.4.1'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
  # guard
  gem 'guard', '1.3.2'
  gem 'guard-spork', '1.2.0'
  
  # testing
  gem 'rspec-rails', '2.11.0'
  gem 'factory_girl_rails', '4.1.0'
  gem 'database_cleaner', '0.8.0'
  gem 'rb-fsevent', '~> 0.9.1'
  gem 'json_spec', '~> 1.0.3'
  
end

group :cucumber do
  gem 'cucumber-rails', '1.3.0'
  gem 'spork', '0.9.2'
  gem 'launchy', '2.1.2'
end

gem 'jquery-rails'
