source :rubygems

gem 'sinatra'

gem 'rake'
gem 'carrierwave'
gem 'carrierwave-datamapper', :require => 'carrierwave/datamapper'

gem 'sidekiq'
gem 'redis'
gem 'datamapper'
gem 'mini_magick'
gem 'dm-postgres-adapter'
gem 'activesupport'

group :test do
  gem 'rspec'
  gem 'rack-test', :require => "rack/test"
  gem 'webrat'
  gem 'simplecov', :require => false
end

